repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: check-toml
    -   id: mixed-line-ending
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
        args: [--branch, develop, --branch, main]
    -   id: trailing-whitespace
    -   id: check-docstring-first
    -   id: requirements-txt-fixer
    -   id: pretty-format-json
        args: [--indent=4, --autofix]
    -   id: fix-encoding-pragma
        args: [--remove]
    -   id: check-merge-conflict
        args: [--assume-in-merge]

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black

-   repo: https://github.com/adamchainz/blacken-docs
    rev: 1.13.0
    hooks:
    -   id: blacken-docs
        additional_dependencies:
        - black==22.12.0

-   repo: https://github.com/PyCQA/docformatter
    rev: v1.6.0-rc2
    hooks:
    -   id: docformatter
    -   id: docformatter-venv

-   repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        name: isort (python)
